[package]
name = "rustchain"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"

rand = "0.7"           
rand_core = "0.6.4"    
ed25519-dalek = "1.0.1"